spring:
  datasource:
    username: root
    password: wangyifan52199@
    url: jdbc:mysql://47.111.190.15:3306/zhihu?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      location: D:/xuexi/zhiphoto
      max-request-size: 1000MB
  redis:
    host: 47.111.190.15
    port: 6379
    password: wangyifan52199
mybatis:
  type-aliases-package: com.example.demo.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml